<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46619" started-at="2021-12-22T04:39:32 IST" finished-at="2021-12-22T04:40:19 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="46619" started-at="2021-12-22T04:39:32 IST" finished-at="2021-12-22T04:40:19 IST">
      <class name="Academy.LoginPageTestCases">
        <test-method status="PASS" signature="initialize()[pri:0, instance:Academy.LoginPageTestCases@76f2bbc1]" name="initialize" is-config="true" duration-ms="27028" started-at="2021-12-22T04:39:32 IST" finished-at="2021-12-22T04:39:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="invalidCredsTextVerification(java.lang.String,java.lang.String)[pri:9, instance:Academy.LoginPageTestCases@76f2bbc1]" name="invalidCredsTextVerification" duration-ms="10891" started-at="2021-12-22T04:40:00 IST" data-provider="getData" finished-at="2021-12-22T04:40:10 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[amit.arora@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidCredsTextVerification -->
        <test-method status="PASS" signature="invalidCredsTextVerification(java.lang.String,java.lang.String)[pri:9, instance:Academy.LoginPageTestCases@76f2bbc1]" name="invalidCredsTextVerification" duration-ms="7980" started-at="2021-12-22T04:40:11 IST" data-provider="getData" finished-at="2021-12-22T04:40:18 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[ram.sharma@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidCredsTextVerification -->
        <test-method status="FAIL" signature="intentionalFailure()[pri:0, instance:Academy.LoginPageTestCases@76f2bbc1]" name="intentionalFailure" duration-ms="223" started-at="2021-12-22T04:40:19 IST" depends-on-methods="Academy.LoginPageTestCases.invalidCredsTextVerification" finished-at="2021-12-22T04:40:19 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Forgot Password] but found [Forgot Password?]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Forgot Password] but found [Forgot Password?]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Academy.LoginPageTestCases.intentionalFailure(LoginPageTestCases.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intentionalFailure -->
      </class> <!-- Academy.LoginPageTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
